import { createFileRoute, Navigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { changePassword, createAddress, getAuthMe, requestEmailVerification, updateUser, type AuthMeResponse } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";

export const Route = createFileRoute("/minha-conta")({ component: AccountPage });
function AccountPage() {
  const { isAuthenticated } = useAuth(); const [profile, setProfile] = useState<AuthMeResponse | null>(null); const [message, setMessage] = useState(""); const [passwords, setPasswords] = useState({ atual: "", nova: "" });
  useEffect(() => { if (isAuthenticated) void getAuthMe().then(setProfile); }, [isAuthenticated]);
  if (!isAuthenticated) return <Navigate to="/login" search={{ redirect: "/minha-conta" }} />;
  if (!profile) return <main className="page-shell py-16">Carregando...</main>;
  async function saveProfile(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await updateUser(profile!.id, { nome: String(data.get("nome")), telefone: String(data.get("telefone")) }); setProfile(await getAuthMe()); setMessage("Perfil atualizado."); }
  async function addAddress(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (!profile!.client_id) return; await createAddress({ client_id: profile!.client_id, rua: String(data.get("rua")), numero: String(data.get("numero")), bairro: String(data.get("bairro")), cidade: String(data.get("cidade")), estado: String(data.get("estado")).toUpperCase(), cep: String(data.get("cep")) }); setProfile(await getAuthMe()); setMessage("Endereço salvo."); }
  return <main className="page-shell py-12"><h1 className="font-display text-4xl font-bold">Minha conta</h1>{message && <p className="mt-4 text-sm text-forest">{message}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-2"><form onSubmit={saveProfile} className="card space-y-4 p-6"><h2 className="text-xl font-bold">Perfil</h2><input className="field-input" name="nome" defaultValue={profile.nome}/><input className="field-input" name="telefone" defaultValue={profile.telefone ?? ""}/><button className="btn-primary">Salvar perfil</button>{!profile.email_verificado && <button type="button" className="btn-secondary ml-2" onClick={() => void requestEmailVerification().then((r) => setMessage(r.message))}>Verificar e-mail</button>}</form><form onSubmit={addAddress} className="card grid grid-cols-2 gap-3 p-6"><h2 className="col-span-2 text-xl font-bold">Endereço</h2>{["rua","numero","bairro","cidade","estado","cep"].map((name) => <input key={name} required className="field-input" name={name} placeholder={name}/>) }<button className="btn-primary col-span-2">Adicionar endereço</button></form><form onSubmit={(e) => { e.preventDefault(); void changePassword(passwords.atual, passwords.nova).then((r) => setMessage(r.message)); }} className="card space-y-4 p-6"><h2 className="text-xl font-bold">Alterar senha</h2><input className="field-input" type="password" placeholder="Senha atual" value={passwords.atual} onChange={(e) => setPasswords({ ...passwords, atual: e.target.value })}/><input className="field-input" type="password" minLength={8} placeholder="Nova senha" value={passwords.nova} onChange={(e) => setPasswords({ ...passwords, nova: e.target.value })}/><button className="btn-primary">Alterar senha</button></form>{profile.endereco && <section className="card p-6"><h2 className="text-xl font-bold">Endereço atual</h2><p className="mt-3 text-muted">{profile.endereco.rua}, {profile.endereco.numero}<br/>{profile.endereco.bairro} — {profile.endereco.cidade}/{profile.endereco.estado}<br/>{profile.endereco.cep}</p></section>}</div></main>;
}
