/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarEmailRouteImport } from './routes/verificar-email'
import { Route as TabelaMedidasRouteImport } from './routes/tabela-medidas'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RastrearPedidoRouteImport } from './routes/rastrear-pedido'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoComprarRouteImport } from './routes/como-comprar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AcompanharPedidoRouteImport } from './routes/acompanhar-pedido'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'
import { Route as AdminPromocoesRouteImport } from './routes/admin/promocoes'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminLancamentosRouteImport } from './routes/admin/lancamentos'
import { Route as AdminComoComprarRouteImport } from './routes/admin/como-comprar'
import { Route as AdminCadastrarProdutoRouteImport } from './routes/admin/cadastrar-produto'
import { Route as AdminPedidosOrderIdRouteImport } from './routes/admin/pedidos.$orderId'

const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar-email',
  path: '/verificar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelaMedidasRoute = TabelaMedidasRouteImport.update({
  id: '/tabela-medidas',
  path: '/tabela-medidas',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RastrearPedidoRoute = RastrearPedidoRouteImport.update({
  id: '/rastrear-pedido',
  path: '/rastrear-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoComprarRoute = ComoComprarRouteImport.update({
  id: '/como-comprar',
  path: '/como-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharPedidoRoute = AcompanharPedidoRouteImport.update({
  id: '/acompanhar-pedido',
  path: '/acompanhar-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/admin/promocoes',
  path: '/admin/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLancamentosRoute = AdminLancamentosRouteImport.update({
  id: '/admin/lancamentos',
  path: '/admin/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComoComprarRoute = AdminComoComprarRouteImport.update({
  id: '/admin/como-comprar',
  path: '/admin/como-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastrarProdutoRoute = AdminCadastrarProdutoRouteImport.update({
  id: '/admin/cadastrar-produto',
  path: '/admin/cadastrar-produto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosOrderIdRoute = AdminPedidosOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminPedidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/promocoes': typeof PromocoesRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/tabela-medidas': typeof TabelaMedidasRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/admin/cadastrar-produto': typeof AdminCadastrarProdutoRoute
  '/admin/como-comprar': typeof AdminComoComprarRoute
  '/admin/lancamentos': typeof AdminLancamentosRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/pedidos/$orderId': typeof AdminPedidosOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/promocoes': typeof PromocoesRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/tabela-medidas': typeof TabelaMedidasRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/admin/cadastrar-produto': typeof AdminCadastrarProdutoRoute
  '/admin/como-comprar': typeof AdminComoComprarRoute
  '/admin/lancamentos': typeof AdminLancamentosRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/pedidos/$orderId': typeof AdminPedidosOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/promocoes': typeof PromocoesRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/tabela-medidas': typeof TabelaMedidasRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/admin/cadastrar-produto': typeof AdminCadastrarProdutoRoute
  '/admin/como-comprar': typeof AdminComoComprarRoute
  '/admin/lancamentos': typeof AdminLancamentosRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/pedidos/$orderId': typeof AdminPedidosOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar-pedido'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/esqueci-senha'
    | '/faq'
    | '/lancamentos'
    | '/login'
    | '/minha-conta'
    | '/promocoes'
    | '/rastrear-pedido'
    | '/redefinir-senha'
    | '/sobre'
    | '/tabela-medidas'
    | '/verificar-email'
    | '/admin/cadastrar-produto'
    | '/admin/como-comprar'
    | '/admin/lancamentos'
    | '/admin/pedidos'
    | '/admin/promocoes'
    | '/pedido/$orderId'
    | '/produto/$id'
    | '/admin/pedidos/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar-pedido'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/esqueci-senha'
    | '/faq'
    | '/lancamentos'
    | '/login'
    | '/minha-conta'
    | '/promocoes'
    | '/rastrear-pedido'
    | '/redefinir-senha'
    | '/sobre'
    | '/tabela-medidas'
    | '/verificar-email'
    | '/admin/cadastrar-produto'
    | '/admin/como-comprar'
    | '/admin/lancamentos'
    | '/admin/pedidos'
    | '/admin/promocoes'
    | '/pedido/$orderId'
    | '/produto/$id'
    | '/admin/pedidos/$orderId'
  id:
    | '__root__'
    | '/'
    | '/acompanhar-pedido'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/esqueci-senha'
    | '/faq'
    | '/lancamentos'
    | '/login'
    | '/minha-conta'
    | '/promocoes'
    | '/rastrear-pedido'
    | '/redefinir-senha'
    | '/sobre'
    | '/tabela-medidas'
    | '/verificar-email'
    | '/admin/cadastrar-produto'
    | '/admin/como-comprar'
    | '/admin/lancamentos'
    | '/admin/pedidos'
    | '/admin/promocoes'
    | '/pedido/$orderId'
    | '/produto/$id'
    | '/admin/pedidos/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanharPedidoRoute: typeof AcompanharPedidoRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ComoComprarRoute: typeof ComoComprarRoute
  ContatoRoute: typeof ContatoRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  FaqRoute: typeof FaqRoute
  LancamentosRoute: typeof LancamentosRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PromocoesRoute: typeof PromocoesRoute
  RastrearPedidoRoute: typeof RastrearPedidoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SobreRoute: typeof SobreRoute
  TabelaMedidasRoute: typeof TabelaMedidasRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  AdminCadastrarProdutoRoute: typeof AdminCadastrarProdutoRoute
  AdminComoComprarRoute: typeof AdminComoComprarRoute
  AdminLancamentosRoute: typeof AdminLancamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-email': {
      id: '/verificar-email'
      path: '/verificar-email'
      fullPath: '/verificar-email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabela-medidas': {
      id: '/tabela-medidas'
      path: '/tabela-medidas'
      fullPath: '/tabela-medidas'
      preLoaderRoute: typeof TabelaMedidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastrear-pedido': {
      id: '/rastrear-pedido'
      path: '/rastrear-pedido'
      fullPath: '/rastrear-pedido'
      preLoaderRoute: typeof RastrearPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-comprar': {
      id: '/como-comprar'
      path: '/como-comprar'
      fullPath: '/como-comprar'
      preLoaderRoute: typeof ComoComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar-pedido': {
      id: '/acompanhar-pedido'
      path: '/acompanhar-pedido'
      fullPath: '/acompanhar-pedido'
      preLoaderRoute: typeof AcompanharPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promocoes': {
      id: '/admin/promocoes'
      path: '/admin/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lancamentos': {
      id: '/admin/lancamentos'
      path: '/admin/lancamentos'
      fullPath: '/admin/lancamentos'
      preLoaderRoute: typeof AdminLancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/como-comprar': {
      id: '/admin/como-comprar'
      path: '/admin/como-comprar'
      fullPath: '/admin/como-comprar'
      preLoaderRoute: typeof AdminComoComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cadastrar-produto': {
      id: '/admin/cadastrar-produto'
      path: '/admin/cadastrar-produto'
      fullPath: '/admin/cadastrar-produto'
      preLoaderRoute: typeof AdminCadastrarProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos/$orderId': {
      id: '/admin/pedidos/$orderId'
      path: '/$orderId'
      fullPath: '/admin/pedidos/$orderId'
      preLoaderRoute: typeof AdminPedidosOrderIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
  }
}

interface AdminPedidosRouteChildren {
  AdminPedidosOrderIdRoute: typeof AdminPedidosOrderIdRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosOrderIdRoute: AdminPedidosOrderIdRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanharPedidoRoute: AcompanharPedidoRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ComoComprarRoute: ComoComprarRoute,
  ContatoRoute: ContatoRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  FaqRoute: FaqRoute,
  LancamentosRoute: LancamentosRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  PromocoesRoute: PromocoesRoute,
  RastrearPedidoRoute: RastrearPedidoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SobreRoute: SobreRoute,
  TabelaMedidasRoute: TabelaMedidasRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  AdminCadastrarProdutoRoute: AdminCadastrarProdutoRoute,
  AdminComoComprarRoute: AdminComoComprarRoute,
  AdminLancamentosRoute: AdminLancamentosRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminPromocoesRoute: AdminPromocoesRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
