/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabelaMedidasRouteImport } from './routes/tabela-medidas'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RastrearPedidoRouteImport } from './routes/rastrear-pedido'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoComprarRouteImport } from './routes/como-comprar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as AdminCadastrarProdutoRouteImport } from './routes/admin/cadastrar-produto'

const TabelaMedidasRoute = TabelaMedidasRouteImport.update({
  id: '/tabela-medidas',
  path: '/tabela-medidas',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RastrearPedidoRoute = RastrearPedidoRouteImport.update({
  id: '/rastrear-pedido',
  path: '/rastrear-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoComprarRoute = ComoComprarRouteImport.update({
  id: '/como-comprar',
  path: '/como-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastrarProdutoRoute = AdminCadastrarProdutoRouteImport.update({
  id: '/admin/cadastrar-produto',
  path: '/admin/cadastrar-produto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/promocoes': typeof PromocoesRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/sobre': typeof SobreRoute
  '/tabela-medidas': typeof TabelaMedidasRoute
  '/admin/cadastrar-produto': typeof AdminCadastrarProdutoRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/promocoes': typeof PromocoesRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/sobre': typeof SobreRoute
  '/tabela-medidas': typeof TabelaMedidasRoute
  '/admin/cadastrar-produto': typeof AdminCadastrarProdutoRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/promocoes': typeof PromocoesRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/sobre': typeof SobreRoute
  '/tabela-medidas': typeof TabelaMedidasRoute
  '/admin/cadastrar-produto': typeof AdminCadastrarProdutoRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/faq'
    | '/lancamentos'
    | '/login'
    | '/promocoes'
    | '/rastrear-pedido'
    | '/sobre'
    | '/tabela-medidas'
    | '/admin/cadastrar-produto'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/faq'
    | '/lancamentos'
    | '/login'
    | '/promocoes'
    | '/rastrear-pedido'
    | '/sobre'
    | '/tabela-medidas'
    | '/admin/cadastrar-produto'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/como-comprar'
    | '/contato'
    | '/faq'
    | '/lancamentos'
    | '/login'
    | '/promocoes'
    | '/rastrear-pedido'
    | '/sobre'
    | '/tabela-medidas'
    | '/admin/cadastrar-produto'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ComoComprarRoute: typeof ComoComprarRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  LancamentosRoute: typeof LancamentosRoute
  LoginRoute: typeof LoginRoute
  PromocoesRoute: typeof PromocoesRoute
  RastrearPedidoRoute: typeof RastrearPedidoRoute
  SobreRoute: typeof SobreRoute
  TabelaMedidasRoute: typeof TabelaMedidasRoute
  AdminCadastrarProdutoRoute: typeof AdminCadastrarProdutoRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabela-medidas': {
      id: '/tabela-medidas'
      path: '/tabela-medidas'
      fullPath: '/tabela-medidas'
      preLoaderRoute: typeof TabelaMedidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastrear-pedido': {
      id: '/rastrear-pedido'
      path: '/rastrear-pedido'
      fullPath: '/rastrear-pedido'
      preLoaderRoute: typeof RastrearPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-comprar': {
      id: '/como-comprar'
      path: '/como-comprar'
      fullPath: '/como-comprar'
      preLoaderRoute: typeof ComoComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cadastrar-produto': {
      id: '/admin/cadastrar-produto'
      path: '/admin/cadastrar-produto'
      fullPath: '/admin/cadastrar-produto'
      preLoaderRoute: typeof AdminCadastrarProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ComoComprarRoute: ComoComprarRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  LancamentosRoute: LancamentosRoute,
  LoginRoute: LoginRoute,
  PromocoesRoute: PromocoesRoute,
  RastrearPedidoRoute: RastrearPedidoRoute,
  SobreRoute: SobreRoute,
  TabelaMedidasRoute: TabelaMedidasRoute,
  AdminCadastrarProdutoRoute: AdminCadastrarProdutoRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
